version: "3.8"

networks:
  web:
    external: true

services:
  shkafconfig:
    image: nginx:alpine
    container_name: shkafconfig
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shkafconfig.rule=Host(`config.kosarev.site`)"
      - "traefik.http.routers.shkafconfig.entrypoints=websecure"
      - "traefik.http.routers.shkafconfig.tls=true"
      - "traefik.http.routers.shkafconfig.tls.certresolver=myresolver"
      - "traefik.http.services.shkafconfig.loadbalancer.server.port=80"

  mailer:
    build: ./mailer
    container_name: shkaf_mailer
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web